name: PersonalPVP
version: ${project.version}
main: xyz.nsgw.personalpvp.PPVPPlugin
api-version: 1.17
authors: [ CosmicSilence ]
website: https://github.com/Nebula-O
softdepend: [PlaceholderAPI]
permissions:
  personalpvp.player:
    children:
      - personalpvp.help
      - personalpvp.togglepvp
      - personalpvp.pvpcontrol
      - personalpvp.toggleactionbar
    default: not op
    description: All default permissions.
  personalpvp.admin:
    default: op
    description: Complete set of PVP permissions.
    children:
    - personalpvp.reload
    - personalpvp.update
    - personalpvp.togglepvp
    - personalpvp.togglepvp.other
    - personalpvp.togglepvp.bypass
    - personalpvp.toggleactionbar
    - personalpvp.pvpcontrol
    - personalpvp.pvpcontrol.admin
    - personalpvp.pvpother
    - personalpvp.resetplayer
    - personalpvp.lock
    - personalpvp.listpvp
    - personalpvp.help
    - personalpvp.listpermissions